### ISSUE TITLE
Parserprobleme mit Kommentarzeichen bei innerhalb von Blöcken referenzierten less Dateien 

### ISSUE THREAD

**Issue by konfusio** [i-net-software/jlessc#23]
Hallo Volker :)

folgende Exception sehe ich nun im aktuellen snapshoot(5b6625ec5bae6dae9f33efcce90f9fa5e7045779) beim generieren:

```
Caused by: java.lang.StringIndexOutOfBoundsException: String index out of range: -1
    at java.lang.AbstractStringBuilder.setCharAt(AbstractStringBuilder.java:380)
    at java.lang.StringBuilder.setCharAt(StringBuilder.java:76)
    at com.inet.lib.less.LessLookAheadReader.back(LessLookAheadReader.java:263)
    at com.inet.lib.less.LessParser.back(LessParser.java:1158)
    at com.inet.lib.less.LessParser.comment(LessParser.java:1137)
    at com.inet.lib.less.LessParser.parseBlock(LessParser.java:284)
    at com.inet.lib.less.LessParser.importFile(LessParser.java:546)
```

nach etwas debugging sieht es danach aus, das Kommentare mit // am Dateianfang problematisch sind, wenn die Datei per @import eingebunden ist, aber nur innerhalb eines Blocks.

```
#baufilead_fancybox .baufilead_dialog {
    @import "dialog-tags.less";
}
```

und die dialog-tags.less mit // beginnt. Unproblematisch sind z.b. /\*  */ Ausdrücke.

VG
Steffen

**Comment by Horcrux7** [comment]
War ja klar, das es nicht so einfach geht.
