### ISSUE TITLE
does jlessc confuse SVG filter names with CSS colors?

### ISSUE THREAD

**Issue by mo** [i-net-software/jlessc#29]
jlessc runs into a LessException when processing SVG filter CSS even though less.js handles these just fine. It seems that jlessc misinterprets the filter names as HTML colors. Maybe this is easy to fix?

I've uploaded an example here, where the regular less.js processes the SVG filter just fine:
http://temp.minimum.se/svg-filter-css.zip

The error I get from jless is:
com.inet.lib.less.LessException: Invalid Color: #wherearemyglasses
     on line 1, column 21
    at com.inet.lib.less.LessObject.createException(LessObject.java:67)
    at com.inet.lib.less.ValueExpression.eval(ValueExpression.java:229)
    at com.inet.lib.less.ValueExpression.appendTo(ValueExpression.java:105)
    at com.inet.lib.less.Expression.stringValue(Expression.java:165)
    at com.inet.lib.less.FunctionExpression.appendTo(FunctionExpression.java:239)
    at com.inet.lib.less.CssFormatter.appendProperty(CssFormatter.java:760)
    at com.inet.lib.less.RuleProperty.appendTo(RuleProperty.java:71)
    at com.inet.lib.less.Rule.appendPropertiesTo(Rule.java:316)
    at com.inet.lib.less.Rule.appendTo(Rule.java:171)
    at com.inet.lib.less.Rule.appendTo(Rule.java:187)
    at com.inet.lib.less.Rule.appendTo(Rule.java:187)
    at com.inet.lib.less.Rule.appendTo(Rule.java:122)
    at com.inet.lib.less.CssFormatter.format(CssFormatter.java:190)
    at com.inet.lib.less.Less.compile(Less.java:81)
    at com.inet.lib.less.Less.compile(Less.java:103)

**Comment by mo** [comment]
Thank you for fixing this! Impressive with the quick turn around time.

**Comment by mo** [comment]
@Horcrux7 I've tried the fix now and it works well. Could you upload a new release to the main maven repository?

**Comment by Horcrux7** [comment]
I have create version 1.5.
