### ISSUE TITLE
Not working in Java SE 7

### ISSUE THREAD

**Issue by joain946** [i-net-software/jlessc#3]
When the released version of the jar file is executed in a Java SE 7 runtime I get this error:
java.lang.UnsupportedClassVersionError: com/inet/lib/less/Less : Unsupported major.minor version 52.0
    at java.lang.ClassLoader.defineClass1(Native Method)
    at java.lang.ClassLoader.defineClass(ClassLoader.java:800)
    at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
    at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
    at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
...

Recompiling with 1.7 compliance level solves the problem.

**Comment by joain946** [comment]
Thank you for your quick response to all my requests.
Everything works perfectly now.

Will you release a new version of all the changes and if so when will that be?
