### ISSUE TITLE
NullPointerException when using compress

### ISSUE THREAD

**Issue by joain946** [i-net-software/jlessc#6]
Everything is working great when not specifying the compress option when compiling.
But with compress I get this error:
com.inet.lib.less.LessException: java.lang.NullPointerException
    at com.inet.lib.less.Less.compile(Less.java:63)
    at com.inet.lib.less.Less.main(Less.java:72)
Caused by: java.lang.NullPointerException
    at com.inet.lib.less.CssFormatter.append(CssFormatter.java:387)
    at com.inet.lib.less.CompressCssFormatter.comment(CompressCssFormatter.java:80)
    at com.inet.lib.less.Comment.appendTo(Comment.java:53)
    at com.inet.lib.less.CssFormatter.format(CssFormatter.java:152)
    at com.inet.lib.less.Less.compile(Less.java:59)
    ... 1 more

This problem can easily be triggered when using Bootstrap 3.2.0 using the "bootstrap.less" file as input.

**Comment by Horcrux7** [comment]
The stacktrace look like version 1.0. Then this checkin https://github.com/i-net-software/jlessc/commit/cebe172a42a0c0a0cc99094ed4eff8057d63f8a2 should have fix it. Please try the version in the repository.
