### ISSUE TITLE
Support hexadecimal alpha colors

### ISSUE THREAD

**Issue by i0n-** [i-net-software/jlessc#61]
The compiler fail on colors format like this:
```
color: #000A,
color: #001122AA;
```
When 'A' denote alpha transparent value.
I get this error on 1.8 version.

```
com.inet.lib.less.LessException: Invalid Color: #000A
	at com.inet.lib.less.LessObject.createException(LessObject.java:67)
	at com.inet.lib.less.ValueExpression.eval(ValueExpression.java:257)
	at com.inet.lib.less.ValueExpression.appendTo(ValueExpression.java:130)
	at com.inet.lib.less.CssFormatter.appendProperty(CssFormatter.java:832)
	at com.inet.lib.less.RuleProperty.appendTo(RuleProperty.java:79)
	at com.inet.lib.less.Rule.appendPropertiesTo(Rule.java:332)
	at com.inet.lib.less.Rule.appendTo(Rule.java:181)
	at com.inet.lib.less.Rule.appendTo(Rule.java:197)
	at com.inet.lib.less.Rule.appendTo(Rule.java:132)
	at com.inet.lib.less.CssFormatter.format(CssFormatter.java:216)
	at com.inet.lib.less.Less.compile(Less.java:135)
	at com.inet.lib.less.Less.compile(Less.java:88)
	at com.inet.lib.less.Less.compile(Less.java:68)

```
Thanks, in advance.

FYI: 
https://developer.mozilla.org/en-US/docs/Web/CSS/color

**Comment by Horcrux7** [comment]
Seems that it is new to CSS Color Module Level 4 which is a working draft.

**Comment by Horcrux7** [comment]
A fix is in the snapshot version available. Please test it.
