### ISSUE TITLE
Processing of uppercase "!IMPORTANT" directives

### ISSUE THREAD

**Issue by aurelien-minvielle** [i-net-software/jlessc#79]
Hello,

Jlessc fails to compile uppercase `!IMPORTANT` directives.

Here's a code sample to reproduce the behaviour:

```
    @Test
    void shouldCompile() throws Exception {
        var less = """
                .foo {
                  width: 2em !IMPORTANT;
                }
                """;

        Less.compile(null, less, false);
    }
```

Actual behaviour:
```

Unrecognized input: '
'
	 on line 3, column 0
com.inet.lib.less.LessException: Unrecognized input: '
'
	 on line 3, column 0
	at com.inet.lib.less.LessObject.createException(LessObject.java:67)
	at com.inet.lib.less.LessParser.createException(LessParser.java:1432)
	at com.inet.lib.less.LessParser.parseSemicolon(LessParser.java:211)
	at com.inet.lib.less.LessParser.parseRule(LessParser.java:645)
	at com.inet.lib.less.LessParser.rule(LessParser.java:628)
	at com.inet.lib.less.LessParser.parseBlock(LessParser.java:300)
	at com.inet.lib.less.LessParser.parse(LessParser.java:162)
	at com.inet.lib.less.LessParser.parse(LessParser.java:123)
	at com.inet.lib.less.Less.compile(Less.java:129)
	at com.inet.lib.less.Less.compile(Less.java:88)
	at com.inet.lib.less.Less.compile(Less.java:68)
```

The error message is not helpful.

!IMPORTANT does not seem spec-compliant : https://www.w3.org/TR/css-syntax-3/#!important-diagram
But it is actually accepted by most browsers (tested on Chrome, Firefox and Safari).

less.js compiler accepts to compile `!IMPORTANT;` (tested on https://lesstester.com/).
It seems to accept any `!XXX;` directive as long as there is a final `;`.

Expected behaviour:
- Either accept it, as less.js does. It would ease migration from the old java binding https://github.com/marceloverdijk/lesscss-java to jlessc,
- Or provide a helpful error message stating the uppercase IMPORTANT keyword is invalid.

**Comment by Horcrux7** [comment]
This fix your sample. But JLessC does not handle it with uppercase. JLessC pass it forward forward as unquoted string. There can be a difference if you want call some less stuff like a mixin because it change the count of parameters.

If you have a more complex sample that does not work like expected then you can reopen. But the my suggestion is to use the right writing.

**Comment by aurelien-minvielle** [comment]
Works for me, thanks for the quick feedback 👍
